### ISSUE TITLE
Error on Firefox

### ISSUE THREAD

**Issue by theomartiz** [danoc/react-use-clipboard#19]
Hello everyone,

I have tested the solution on Firefox but it rejects an error:

`Unhandled Rejection (TypeError): 'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.`

Do you have a solution ?

**Comment by danoc** [comment]
Hi @theomartiz,

I'm not able to reproduce the issue on the latest Firefox for Mac. Here's a small page to test it out:
https://csb-oqi7n-ecwfe6mii.vercel.app/

Does that button throw an error for you? If so, what version of Firefox and which OS are you using?

This library is a thin wrapper of [`copy-to-clipboard`](https://github.com/sudodoki/copy-to-clipboard) so it's likely that the issue is in that codebase.
